components:
  schemas:
    Product:
      type: object
      properties:
        image:
          type: string
          description: URL de la imagen del producto
        title:
          type: string
          description: Título del producto (único)
        description:
          type: string
          description: Breve descripción del producto
        price:
          type: number
          description: Precio en moneda local
        stock:
          type: integer
          description: Unidades disponibles
        category:
          type: string
          description: Categoría del producto
        code:
          type: string
          description: Código único de producto
        status:
          type: boolean
          description: Estado del producto (true = activo)
      example:
        image: /assets/products/image.png
        title: Avion de Guerra
        description: Avion de guerra de la segunda guerra mundial
        price: 20000
        stock: 50
        category: Maquetas
        code: D11
        status: true

paths:
  /api/products:
    get:
      summary: Obtener todos los productos disponibles
      tags: [Products]
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor

    post:
      summary: Crear un nuevo producto
      tags: [Products]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Producto creado exitosamente
        '500':
          description: Error interno del servidor

  /api/products/{pid}:
    get:
      summary: Obtener un producto por su ID
      tags: [Products]
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto encontrado
        '500':
          description: Error interno del servidor

    put:
      summary: Actualizar un producto por su ID
      tags: [Products]
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Producto actualizado
        '500':
          description: Error interno del servidor

    delete:
      summary: Eliminar un producto por su ID
      tags: [Products]
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado
        '500':
          description: Error interno del servidor

  /api/products/title/{title}:
    get:
      summary: Obtener producto por título
      tags: [Products]
      parameters:
        - name: title
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto encontrado
        '500':
          description: Error interno del servidor